<<<<<<< HEAD
# Generated by Django 4.2.20 on 2025-06-02 20:58
=======
# Generated by Django 4.2.20 on 2025-06-02 20:52
>>>>>>> da5f83008240203e9682b2762db6b41d629bb771

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezepty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
    ]
